version: 0.2

phases:
  install:
    commands:
      - echo Installing phase started

  pre_build:
    commands:
      - echo Pre-build phase

  build:
    commands:
      - echo Build started
      - docker build -t myapp .
      - docker run myapp

  post_build:
    commands:
      - echo Build completed successfully
